'use client';

// import type { Metadata } from 'next';
import { Suspense } from 'react';
import StyledComponentsRegistry from '../utils/styledComponentsRegistry';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { ConfigProvider, Layout, App } from 'antd';
import styled from 'styled-components';
import PageLayout from '../components/layout';
import './globals.css';

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

const jetBrains = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-jetbrains",
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

const ContainerLayout = styled(Layout)`
	min-height: 100vh;
`;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={ `${inter.variable} ${jetBrains.variable}` }>
			<body className={ inter.className }>
				<StyledComponentsRegistry>
					<App>
						<ContainerLayout>
							<PageLayout>
								<Suspense>
									{ children }
								</Suspense>
							</PageLayout>
						</ContainerLayout>
					</App>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
